### ISSUE TITLE
Publish Page Refresh

### ISSUE THREAD

**Issue by Nopfed** [Nopfed/godot-arcade#13]
Due to new update to ArConnect wallets, there is an issue when trying to get to the publish page after a wallet has already been connected once before, either due to refreshing or re-navigating back to the publish page. 

Gets the following:  "Error connecting. App already has all permissions requested"

Need to look into new code for the page to update when the wallet is already connected as it is not currently updating automatically and does not let you get to publish page even when wallet is connected.

**Comment by jim-toth** [comment]
#16
